{
 "title": "Goapp",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "summary",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "golang_my_summary{}" }
   ]
  },
  {
   "title": "Gauge",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "golang_my_gauge{}" }
   ]
  },
  {
   "title": "Counter ",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "golang_my_counter{}" }
   ]
  },
  {
   "title": "Histogram bucket",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "golang_my_histogram_bucket{}" }
   ]
  }
 ]
}