apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: webapp1
        image: shamalskk/final-go-app-log1:latest
        ports: 
        - containerPort: 8080
     