apiVersion: v1
kind: Service
metadata:
  name: goapp-svc
  namespace: default
  labels:
    app: goapp
    release: prometheus
spec:
  selector:
    app: goapp
  ports:
  - name: web 
    port: 30001
    protocol: TCP
    targetPort: 8080