apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goapp
  namespace: default
  labels:
    release: prometheus
spec:
  endpoints:
  - path: /metrics
    port: web
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: goapp
      release: prometheus